# Teste de Hipotese - Z

In [31]:
import numpy as np
import math
from scipy.stats import norm
from scipy.stats import ttest_rel

In [2]:
dados_originais = np.array([126. , 129.5, 133. , 133. , 136.5, 136.5, 140. , 140. , 140. ,
                            140. , 143.5, 143.5, 143.5, 143.5, 143.5, 143.5, 147. , 147. ,
                            147. , 147. , 147. , 147. , 147. , 150.5, 150.5, 150.5, 150.5,
                            150.5, 150.5, 150.5, 150.5, 154. , 154. , 154. , 154. , 154. ,
                            154. , 154. , 154. , 154. , 157.5, 157.5, 157.5, 157.5, 157.5,
                            157.5, 157.5, 157.5, 157.5, 157.5, 161. , 161. , 161. , 161. ,
                            161. , 161. , 161. , 161. , 161. , 161. , 164.5, 164.5, 164.5,
                            164.5, 164.5, 164.5, 164.5, 164.5, 164.5, 168. , 168. , 168. ,
                            168. , 168. , 168. , 168. , 168. , 171.5, 171.5, 171.5, 171.5,
                            171.5, 171.5, 171.5, 175. , 175. , 175. , 175. , 175. , 175. ,
                            178.5, 178.5, 178.5, 178.5, 182. , 182. , 185.5, 185.5, 189., 192.5])

In [3]:
# Media das alturas de 2019
H0_media = np.mean(dados_originais) # Hipotese nula ou valor ja existente
H0_media

159.25

In [4]:
H0_desvio_padrao = np.std(dados_originais)
H0_desvio_padrao

13.65

In [5]:
# Validando os valores das alturas, pois, agora temos novos dados para o ano de 2020
dados_novos = dados_originais * 1.03 # fazendo uma simulação para ter uma mudança dos valores
dados_novos

array([129.78 , 133.385, 136.99 , 136.99 , 140.595, 140.595, 144.2  ,
       144.2  , 144.2  , 144.2  , 147.805, 147.805, 147.805, 147.805,
       147.805, 147.805, 151.41 , 151.41 , 151.41 , 151.41 , 151.41 ,
       151.41 , 151.41 , 155.015, 155.015, 155.015, 155.015, 155.015,
       155.015, 155.015, 155.015, 158.62 , 158.62 , 158.62 , 158.62 ,
       158.62 , 158.62 , 158.62 , 158.62 , 158.62 , 162.225, 162.225,
       162.225, 162.225, 162.225, 162.225, 162.225, 162.225, 162.225,
       162.225, 165.83 , 165.83 , 165.83 , 165.83 , 165.83 , 165.83 ,
       165.83 , 165.83 , 165.83 , 165.83 , 169.435, 169.435, 169.435,
       169.435, 169.435, 169.435, 169.435, 169.435, 169.435, 173.04 ,
       173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 ,
       176.645, 176.645, 176.645, 176.645, 176.645, 176.645, 176.645,
       180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 183.855,
       183.855, 183.855, 183.855, 187.46 , 187.46 , 191.065, 191.065,
       194.67 , 198.

In [6]:
H1_media = np.mean(dados_novos)
H1_media

164.0275

Logo ouve a mudança da média

In [8]:
H1_std = np.std(dados_novos)
H1_std

14.0595

In [10]:
H1_n = len(dados_novos)
H1_n

100

In [11]:
alpha = 0.05 # nível de confiança

### Teste manual

In [12]:
Z = (H1_media - H0_media)/(H1_std/ math.sqrt(H1_n))
Z

3.398058252427187

Consultando a tabela Z:

In [15]:
norm.cdf(3.398058252427187) # probabilidade cumulativa

0.9996606701617486

In [16]:
norm.ppf(0.9996606701617486) # Buscando o valor de Z

3.3980582524271936

In [17]:
Z = norm.cdf(Z)
Z

0.9996606701617486

In [18]:
p = 1 - Z 
p

0.00033932983825135654

In [20]:
if p < alpha:
    print("Hipotese nula rejeitada. Logo, o novo valor será o cálculado.")
else:
    print("A hipotese alternativa rejeitada.")

Hipotese nula rejeitada. Logo, o novo valor será o cálculado.


### Teste utilizando o statsmodels

In [21]:
from statsmodels.stats.weightstats import ztest

In [22]:
_, p = ztest(dados_originais, 
             dados_novos,
             value = H1_media - H0_media, 
             alternative='larger')

In [23]:
p

0.9999993877283934

In [25]:
if p < alpha:
    print("Hipotese nula rejeitada. Logo, o novo valor será o cálculado.")
else:
    print("A hipotese alternativa rejeitada.")

A hipotese alternativa rejeitada.


### Exercício

In [29]:
dados = np.array([149. , 160., 147., 189., 175., 168., 156., 160., 152.])
dados

array([149., 160., 147., 189., 175., 168., 156., 160., 152.])

In [32]:
data = dados * 1.3
data

array([193.7, 208. , 191.1, 245.7, 227.5, 218.4, 202.8, 208. , 197.6])

In [34]:
_, p = ttest_rel(dados, data)

In [35]:
p

4.072922493929878e-10

In [36]:
alpha = 0.01
if p <= alpha:
    print("Hipotese nula rejeitada")
else:
    print("Hipotese alternativa rejeitada")

Hipotese nula rejeitada


Logo, considerariamos a hipotese nula rejeitada. Dessa forma, estariamos confirmando e aceitando a nova hipotese que estava sendo proposta.